### ISSUE TITLE
Run tests against all versions of python and some of pylint

### ISSUE THREAD

**Issue by michael-k** [pyfocus/pylava_pylint#2] opened 2018-08-27 19:06 UTC
I'm working on this, but cannot assign it to me due to missing rights

**Comment by susam** [comment] 2018-08-28 03:07
Hi @michael-k,

Tests against different versions of Python and that of Pylint is going to be very useful to detect regressions. Thanks for creating this issue.

I have added you as a collaborator to the `pylava_pylint` repo. You should be able to assign this issue to yourself now.

**Closed** 2018-08-28 06:06 UTC

**Comment by susam** [comment] 2018-08-28 06:33
The new build matrix looks nice. Inclusion of `pylintmaster` in the tests is especially nice because it will ensure that this extension is always up-to-date with the latest `pylint`. Thanks for doing this. 

By the way, on a different topic, your membership in this org account is private right now. For example, if you visit https://github.com/pyfocus without being logged in, you do not appear under the "People" section in the sidebar. If you want to make your membership public, please visit https://github.com/orgs/pyfocus/people, click on the drop-down list for your handle, and set it to "Public".

**Comment by michael-k** [comment] 2018-08-28 07:04
> Inclusion of `pylintmaster` in the tests is especially nice because it will ensure that this extension is always up-to-date with the latest `pylint`.

Since I don't expect much activity in this reps, I've added a cron job to travis to ensure we capture incompatibilities as early as possible: https://travis-ci.com/pyfocus/pylava_pylint/settings

> your membership in this org account is private right now

Yes, I know.  I've set it to private for all my memberships and I'm also hiding private contributions from my profile.  I might change that in the future, but for now I prefer it this way.
